site_name: USGS Astrogeology Software Docs

theme:
    name: material
    custom_dir: custom_theme/
    icon:
      annotation: material/chevron-right-circle
    font:
      text: Inter
      code: Roboto Mono
    
    features:
        - navigation.tabs
        - navigation.path
        - navigation.indexes
        - search.suggest
        - search.suggest

    palette:
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          accent: light blue
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          accent: light blue
          toggle:
            icon: material/toggle-switch
            name: Switch to dark mode


nav:
  - Home: index.md
  - Getting Started: 
    - Home: getting-started/index.md
    - CSM Stack:
      - Generating an ISD, creating a CSM model, and converting coordinates: getting-started/CSM Stack/ImageToGroundTutorial.ipynb
    - "Using ISIS: First Steps":
      - Locating and Ingesting Image Data: "getting-started/Using ISIS: First Steps/Locating and Ingesting Image Data.md"
      - Adding SPICE: "getting-started/Using ISIS: First Steps/Adding Spice.md"
      - Exporting ISIS Data: "getting-started/Using ISIS: First Steps/Exporting ISIS Data.md"
  - How-To Guides: 
    - Home: how-to-guides/index.md
    - Environment Setup and Maintenance:
      - Installing ISIS Via Anaconda: how-to-guides/Environment Setup and Maintenance/Installing ISIS Via Anaconda.md
      - Anaconda in a Network Environment: how-to-guides/Environment Setup and Maintenance/Anaconda in a Network Environment.md
      - SPICE Kernel Updates in ISIS: how-to-guides/Environment Setup and Maintenance/SPICE Kernel Updates in ISIS.md
    - SPICE: 
      - Creating Spice Config Files in SpiceQL: how-to-guides/SPICE/Creating Spice Config Files in SpiceQL.md
    - Image Processing:
      - Map Projecting Images: how-to-guides/Image Processing/Map Projecting Images.md
      - Removing Striping Noise: how-to-guides/Image Processing/Removing Striping Noise.md
      - General Utility with FX: how-to-guides/Image Processing/General Utility with FX.md
    - Software Management: 
      - ISIS Public Release Process: how-to-guides/Software Management/Public Release Process.md
      - Software Support: how-to-guides/Software Management/Software Support.md
      - Guidelines for Reporting Issues: how-to-guides/Software Management/Guidelines for Reporting Issues.md
    - ISIS Developer Guides:
      - How To Write ISIS Tests with CTest and GTest: how-to-guides/ISIS Developer Guides/Writing ISIS Tests with CTest and GTest.md
      - App Testing CookBook: how-to-guides/ISIS Developer Guides/App Testing Cookbook.md
      - Class Requirements For Using Doxygen Tags: how-to-guides/ISIS Developer Guides/Class Requirements For Using Doxygen Tags.md
      - Developing ISIS3 with cmake: how-to-guides/ISIS Developer Guides/Developing ISIS3 with cmake.md
  - Concepts: 
    - Home: concepts/index.md
    - Glossary: concepts/glossary/glossary.md
    - Camera Geometry and Projections:
      - Camera Geometry: concepts/Camera Geometry and Projections/Camera Geometry.md
      - Learning About Map Projections: concepts/Camera Geometry and Projections/Learning About Map Projections.md
    - SPICE:
      - SPICE Overview: concepts/SPICE/SPICE Overview.md
      - SPICE Position Functions and Requirements: concepts/SPICE/SPICE Position Functions and Requirements.md
    - Image Processing:
      - The Power of Spatial Filters: concepts/Image Processing/The Power of Spatial Filters.md
      - Overview of Noise and Artifacts: concepts/Image Processing/Overview of Noise and Artifacts.md
      - Overview of Radiometric Calibration: concepts/Image Processing/Overview of Radiometric Calibration.md
  - Manuals: manuals/index.md

extra_css:
  - css/neoteroi-mkdocs.css
  - css/extras.css
  - https://asc-public-docs.s3.us-west-2.amazonaws.com/common/uswds/3.6.0/css/common.css
  - https://asc-public-docs.s3.us-west-2.amazonaws.com/common/uswds/3.6.0/css/custom.css


extra_javascript: 
  -  https://asc-public-docs.s3.us-west-2.amazonaws.com/common/uswds/3.6.0/js/uswds-init.min.js

plugins:
  - search
  - mkdocs-jupyter:
      include_source: true

markdown_extensions:
  - neoteroi.cards
  - abbr
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      title: On this page
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
        auto_append:
          - definitions.md
